trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  displayName: Checkout repository

- script: docker run -t -v .:/scanpath hounddogai/scanner:staging hounddog scan
  displayName: Run HoundDog.ai scan
