pipelines:
  branches:
    main:
      - step:
          name: Run HoundDog.ai Scan
          image: hounddogai/scanner:staging
          script:
            - hounddog scan --output-format=console --fail-severity-threshold=critical
