version: '2'
services:
  front:
    build: ./front
    ports:
      - 4200:4200
    depends_on:
      - web
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: sample_db
    image: postgres:9.5
    volumes:
      - sample_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=sample
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  sample_db: { }
