name: HoundDog.ai Scan (GitHub Action)
on:
  workflow_dispatch:
    debug:
      type: boolean
      description: Debug this workflow via SSH
      default: false
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    container:
      image: hounddogai/scanner:staging
    # Skip pull requests created by dependabot
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Debug workflow via SSH
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Clear code scanning alerts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/clear_github_scan_results.py

      - name: Run HoundDog.ai scan
        uses: hounddogai/hounddog-action@v1
        with:
          output_format: sarif
          output_filename: hounddog.sarif
        continue-on-error: true

      - name: Upload scan results to GitHub Advanced Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hounddog.sarif
        continue-on-error: true
