name: SARIF Test
on:
  push:
    branches:
      - main
    paths:
      - sarif-test-results.sarif
  workflow_dispatch:
jobs:
  hounddog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upload results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif-test-results.sarif
